# Generated by Django 6.0.7 on 2026-08-03 06:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_enable_row_level_security"),
        ("employees", "0003_enable_row_level_security"),
        ("locations", "0002_enable_row_level_security"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attendance_date", models.DateField()),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "check_in_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "check_in_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("check_in_device_id", models.CharField(blank=True, max_length=255)),
                ("check_in_is_mock", models.BooleanField(default=False)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "check_out_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "check_out_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "check_out_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("check_out_device_id", models.CharField(blank=True, max_length=255)),
                ("check_out_is_mock", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("LATE", "Late"),
                            ("EARLY_DEPARTURE", "Early Departure"),
                            ("ABSENT", "Absent"),
                            ("OVERTIME", "Overtime"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("working_minutes", models.PositiveIntegerField(default=0)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("early_departure_minutes", models.PositiveIntegerField(default=0)),
                ("overtime_minutes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="locations.branch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employees.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-attendance_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "employee", "-attendance_date"],
                        name="attendance__organiz_500302_idx",
                    ),
                    models.Index(
                        fields=["organization", "branch", "attendance_date"],
                        name="attendance__organiz_398c32_idx",
                    ),
                    models.Index(
                        fields=["organization", "attendance_date", "status"],
                        name="attendance__organiz_4baa5c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "attendance_date"),
                        name="unique_attendance_per_employee_per_day",
                    )
                ],
            },
        ),
    ]
