# Generated by Django 6.0.7 on 2026-08-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_enable_row_level_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("ATTENDANCE", "Attendance"),
                    ("LEAVE", "Leave"),
                    ("SECURITY", "Security"),
                    ("SUBSCRIPTION", "Subscription"),
                    ("SYSTEM", "System"),
                ],
                max_length=20,
            ),
        ),
    ]
