# Generated by Django 6.0.7 on 2026-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("default_trial_days", models.PositiveIntegerField(default=14)),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Platform settings",
            },
        ),
    ]
