# Generated by Django 6.0.7 on 2026-08-03 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MOCK_LOCATION_DETECTED", "Mock location detected"),
                            ("IMPLAUSIBLE_TRAVEL_SPEED", "Implausible travel speed"),
                            (
                                "CROSS_TENANT_ACCESS_ATTEMPT",
                                "Cross-tenant access attempt",
                            ),
                            ("ACCOUNT_LOCKED", "Account locked"),
                            ("NEW_DEVICE_LOGIN", "New device login"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="security_ev_organiz_bd07aa_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="security_ev_event_t_28b8f3_idx",
                    ),
                ],
            },
        ),
    ]
