# Generated by Django 6.0.7 on 2026-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_device_loginhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="profile_picture_url",
            field=models.URLField(blank=True),
        ),
    ]
