# Generated by Django 6.0.7 on 2026-08-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_enable_row_level_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="grace_period_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Days an organization keeps login access after a subscription on this plan expires, before it is auto-suspended — see Phase 8's expiry job.",
            ),
        ),
    ]
